### ISSUE TITLE
What's your most embarrassing podcast moment?

### ISSUE THREAD

**Issue by greydnls** [jcarouth/ama#10]

**Comment by jcarouth** [comment]
Hm. That's a good question. I'm pretty terrible at podcasting. Some things that come to mind:
1. One time I went through an entire broadcast of our podcast using the built-in mic while still speaking into my better mic. When someone told me towards the end I felt like an incompetent fool.
2. Also on Google Hangouts I once clicked on my own picture which meant my co-host was never video switched too. I haven't dared watch the video to see what sort of weird things I did while I wasn't talking.

And I have no idea how many idiot things I've said over the past year or so. I know I ramble a lot and I'm sure there are plenty of gems in previous episodes. But I try not to listen to myself.
