### ISSUE TITLE
What's the best part about your job?

### ISSUE THREAD

**Issue by aretecode** [jcarouth/ama#14]

**Comment by jcarouth** [comment]
I think my answer is going to be that I enjoy having the opportunity to make the present awesome while shaping the future. Part of what I do these days is solve problems created by prior decisions. The decisions at the time could have been very correct but now the product needs to go a different or, often, in a more consistent direction. So my job is to sort that out and figure out a) how we can get there as quickly as possible and b) where these decisions we make today will put us in the future.

It's neat to think that there is code (likely horrendous, horrible code) I wrote 3, 4, 10 years ago that's still solving a problem for a business or a person. I'm not changing the world but I at least feel like I'm doing something valuable.
