### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [jcarouth/ama#16]

**Comment by jcarouth** [comment]
Hi @jedireza thanks for the question.

I do participate in mentoring of others. I have been involved in the [PHP Mentoring](http://phpmentoring.org/) organization for quite some time. I also have mentored several people out of band with that particular group.

The best part of mentoring is actually learning more about yourself and using your skills and knowledge in new ways. I highly encourage everyone to both find a mentor and to be a mentor.
