### ISSUE TITLE
What did you have for breakfast?

### ISSUE THREAD

**Issue by arthurvr** [jcarouth/ama#3]

**Comment by jcarouth** [comment]
I had leftovers. That sounds really boring. But it was my amazing cauliflower bacon hash with sunny-side-up eggs. Picture for reference (not exactly the plate I had this morning but it'll do.)

![](https://scontent-dfw1-1.cdninstagram.com/hphotos-xaf1/t51.2885-15/e35/11887183_879745038783591_558254790_n.jpg)
