### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by mxriverlynn** [jcarouth/ama#4]

**Comment by jcarouth** [comment]
![](http://3.bp.blogspot.com/-rtkXZjF_gTQ/UO897hwLzfI/AAAAAAAACdc/fpRIgc1jvg8/s1600/Curiosity.png)

**Comment by jcarouth** [comment]
Why not, @derickbailey? Why not?

**Comment by mxriverlynn** [comment]
lol! i fully expected "because" ... but this was far better :D
