### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [jcarouth/ama#5]
Editor, terminal, tools, themes, fonts, process, etc.

**Comment by jcarouth** [comment]
Great question. Let's see if I can answer this.
- I work on Mac. I have an iMac, a 2011 MacBook Pro, and a 2015 MacBook Pro.
- I use iTerm2 and bash. I use [bash-it](https://github.com/jcarouth/bash-it) which is a self-professed shameless rip off of oh-my-zsh.
- I use Vim as my primary editor (Not-so-well-maintained configuration [here](https://github.com/jcarouth/vimrc).) I also have licenses for PHPStorm and RubyMine which I use when I need a little more power in an IDE.
- My color scheme is a high contrast solarized dark scheme
- I switch fonts around a bit. I use Monaco, Inconsolata, and Droid Sans Mono. Of those I think Inconsolata is my favorite.
- I would die if I didn't have tmux.
- I use Vagrant for damn near everything. I forgot what it's like to not work with a VM.
- I love SequelPro for database interaction.
- I have a license for [Kaleidoscope](http://www.kaleidoscopeapp.com/) and it is my merge tool of choice
- [Postman](https://www.getpostman.com/) is invaluable for API development.
- I use ScreenHero for screen sharing.

That's pretty much the extent of it. Everything else depends on the project, language, etc.
