### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by matthewtrask** [jcarouth/ama#6]
Best advice you can give to up and coming developers?

**Comment by jcarouth** [comment]
It works is not the end of your job. It's important to realize that code is read more often than it is written. Once you have functional completeness it's time to work the code to a point it is readable, understandable, and maintainable. Even if you never plan to touch it again code that is cleaned up is a sign of a professional developer.

Also, take some time to experiment. You'll learn something and you'll most likely end up with a better solution. Experimenting with other languages and other frameworks will help you learn how to write more elegant code.
