### ISSUE TITLE
What's one programming habit you wish you could automatically instill in everyone who codes on the planet

### ISSUE THREAD

**Issue by Achocholacek** [jcarouth/ama#7]
aka if you could make it so everyone automatically used PSR2 formatting, or something like that, what would you do?

**Comment by jcarouth** [comment]
I think I want to answer this one like this: if I could instill anything in everyone who writes software it would be effective error handling skills. There is nothing worse than having errors in production and having no way to figure them out. I don't know if that exactly qualifies as an answer to your question but that is what I think everyone should learn.
