### ISSUE TITLE
First actions with new code base

### ISSUE THREAD

**Issue by tristanbailey** [jcarouth/ama#8]
If you start a new job or project to a company project you are handed on Monday. What are the first things you would want to do by Friday for you and would you give your team to do (say one or two other devs) ?

**Comment by jcarouth** [comment]
I think I have a fairly boring answer for this one...

The first part of any project (assuming you mean this is a greenfield, from-nothing project and not just a project within a larger project) is almost always going to be getting the project source set up in all environments. For me this means having a way to consistently develop locally, having a staging environment to work against and making the project compatible with deployment systems. This also means getting the infrastructure set up for continuous integration (testing, linting, standard checks, etc.) and will obviously vary with language/framework/etc.

Luckily a lot of that work is fairly easy to standardize with things like Travis, [Scripts to Rule Them All](https://github.com/github/scripts-to-rule-them-all), and such. So hopefully that wouldn't take the entire week.

After getting this type of thing set up it's time to move on to making sure the whole project team is in sync and understands the problem domain. This would take the form of having a discussion with stakeholders and identifying risks, challenges, goals, etc of the project. Then time would be focused on getting tasks/issues/stores/whatever you want to call them organized and ready for work. Then an agreement reached and work would start.

That is hopefully how the first week of any project goes. My priorities would be to unblock all participants as quickly as possible. Hence the reason I like to answer questions about the source repo(s) and infrastructure up front and then ensure that everyone (stakeholders, product managers, project managers, team leads, developers, designers, ux engineers, etc.) all are talking about the same thing. If you can nail that down early your project has a higher likelihood of success.

**Comment by tristanbailey** [comment]
Thanks for your answer and thoughts. Reading back my question I think I wasn't so clear. I mean you are given a code base project that is live code but you haven't seen before.

**Comment by jcarouth** [comment]
Ah, well that changes my answer a bit then.

For existing projects it's going to vary depending on what we're supposed to be doing with it. If the project is dumped as a "maintain this" project I'm going to spend some time learning about the application; finding hotspots in terms of errors, code churn, problematic libraries or packages, etc; and setting up any monitoring/logging infrastructure as quickly as possible.

If we're tasked with adding something or fixing the project in some way we'll do a lot of the same things but it will be more focused on the specific areas we'll be working in.

Second order of business is likely going to be trying to get some tests going. Characterization tests are your friend when working in an unknown codebase. If there are tests in the application, great. We'll spend some time looking over those to learn as much as we can about the codebase.

Then the rest of my answer above applies. Basically the first bit of time with existing code will just be analysis trying to figure out where things are, and where there are dragons lurking. With projects built on known projects with known conventions this is a lot easier, except for when it's not. Programming is hard.
